def test_fake():
    raise Exception
